
version: "3.8"
services:
  api:
    container_name: dev_exchange
    build:
      context: .
      dockerfile: ./compose/dev/Dockerfile
    ports:
      - 8000:8000
    environment:
      - DATABASE_HOSTNAME=${DATABASE_HOSTNAME}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
    volumes:
      - ./:/usr/src/app
    depends_on:
      - exchange


  exchange:
    image: postgres:14-alpine
    container_name: dev_db_exchange
    ports:
      - 5432:5432
    environment:
      - POSTGRES_HOST_AUTH_METHOD=password
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - db-exchange:/var/lib/postgresql/data

volumes:
  db-exchange:

  