
version: "3.8"
services:
  api:
    container_name: dev_exchange
    build:
      context: .
      dockerfile: ./compose/dev/Dockerfile
    ports:
      - 8000:8000
    env_file:
      - ./.env
    volumes:
      - ./:/usr/src/app
    depends_on:
      - exchange


  exchange:
    image: postgres:14-alpine
    container_name: dev_db_exchange
    ports:
      - 5432:5432
    env_file:
      - ./.env
    volumes:
      - db-exchange:/var/lib/postgresql/data

volumes:
  db-exchange:

  