
version: "3"
services:
  api:
    container_name: dev_exchange
    build:
      context: .
      dockerfile: ./compose/dev/Dockerfile
    ports:
      - 8000:8000
    links:
      - postgres:postgres
    volumes:
      - ./:/usr/src/app
    # depends_on:
    #   - postgres


#   postgres:
#     image: postgres
#     container_name: dev_postgres
#     ports:
#       - 5432:5432
#     environment:
#       - POSTGRES_HOST_AUTH_METHOD=password
#       - POSTGRES_DB=pyfintech
#       - POSTGRES_PASSWORD=password123
#     volumes:
#       - postgres-db:/var/lib/postgresql/data

# volumes:
#   postgres-db:

  